language: node_js
node_js:
  - 8.11.4
before_install:
  - npm install -g npm@6.4.1
  - npm -v
install:
  - npm cache clean --force
  - rm -rf node_modules
  - npm install --save
  - cd functions/
  - npm install --save
  - cd ../

before_script:
  - npm install -g firebase-tools
  - firebase use development --token $FIREBASE_TOKEN
  - firebase deploy --only firestore --token $FIREBASE_TOKEN
  - chmod +x build.sh
script:
  - CI=true
  - npm test
  - CI=false
  - ./build.sh

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log

notifications:
  slack:
    rooms:
      - satudora-digital:xu642Khfs0IkBnmaa6pGPqgv#ci
    on_pull_requests: false
    on_success: change
    on_failure: always

before_deploy:
  - firebase use
  - chmod +x firebase_deploy.sh

deploy:
  provider: script
  script: ./firebase_deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
